---
# Crash Course Python for Data Science - Intro to Python  
---
# 06 - Numpy
---



## STOP! BEFORE GOING ANY FURTHER...  

Remember, this exercises are open book, open neighbour, open everything! Try to do them on your own before looking at the solution samples.



### Import Numpy as Np

In [1]:
# Make sure you run this cell first
import numpy as np
print('NumPy imported!')

NumPy imported!


### Generate random numbers
Create a (5,3) Numpy array of random integer values between 0 and 100.

In [2]:
### YOUR CODE GOES HERE ###

In [3]:
#@title Double click here for a sample solution

x = np.random.randint(0,100, (5,3))
x

array([[47, 17, 33],
       [39, 97, 70],
       [36, 68, 79],
       [92,  5, 74],
       [29, 39,  6]])

### Array practice

In [4]:
# Return the first row:

### YOUR CODE GOES HERE ###

In [5]:
#@title Double click here for a sample solution

# Return the first row:
x[0,]

array([47, 17, 33])

In [6]:
# Return last column

### YOUR CODE GOES HERE ###

In [7]:
#@title Double click here for a sample solution

# Return last column
x[:, -1]

array([33, 70, 79, 74,  6])

In [8]:
# Return the third column values from the 4th and 5th rows

### YOUR CODE GOES HERE ###

In [9]:
#@title Double click here for a sample solution

# Return the third column values from the 4th and 5th rows
x[3:5,2]

array([74,  6])

In [10]:
# Multiply every value in the array by 2

### YOUR CODE GOES HERE ###

In [11]:
#@title Double click here for a sample solution

# Multiply every value in the array by 2
x*2

array([[ 94,  34,  66],
       [ 78, 194, 140],
       [ 72, 136, 158],
       [184,  10, 148],
       [ 58,  78,  12]])

In [12]:
# Divide every value by 3

### YOUR CODE GOES HERE ###

In [13]:
#@title Double click here for a sample solution

# Divide every value by 3
x/3

array([[15.66666667,  5.66666667, 11.        ],
       [13.        , 32.33333333, 23.33333333],
       [12.        , 22.66666667, 26.33333333],
       [30.66666667,  1.66666667, 24.66666667],
       [ 9.66666667, 13.        ,  2.        ]])

In [14]:
# Increase the values in the first row by 12

### YOUR CODE GOES HERE ###

In [15]:
#@title Double click here for a sample solution

# Increase the values in the first row by 12
x[0,] = x[0,] + 12
x

array([[59, 29, 45],
       [39, 97, 70],
       [36, 68, 79],
       [92,  5, 74],
       [29, 39,  6]])

In [16]:
# Calculate the mean of the first column

### YOUR CODE GOES HERE ###

In [17]:
#@title Double click here for a sample solution

# Calculate the mean of the first column
x[:,0].mean()

51.0

In [18]:
# Calculate the median of the array after removing the 2 smallest values in the array

### YOUR CODE GOES HERE ###

In [19]:
#@title Double click here for a sample solution

# Calculate the median of the array after removing the 2 smallest values in the array
x1 = np.delete(x, x.argmin())
x1 = np.delete(x1, x1.argmin())
np.median(x1)


59.0

In [20]:
# Calculate the standard deviation of the first 3 rows

### YOUR CODE GOES HERE ###

In [21]:
#@title Double click here for a sample solution

# Calculate the standard deviation of the first 3 rows
np.std(x[:3],)

21.24460715883759

In [22]:
# Return values in the second column greater than 25

### YOUR CODE GOES HERE ###

In [23]:
#@title Double click here for a sample solution

# Return values in the second column greater than 25
print("Values bigger than 25 on the second column =", x[:,1][x[:,1]>25])

Values bigger than 25 on the second column = [29 97 68 39]


In [24]:
# Return values in the array under 40

### YOUR CODE GOES HERE ###

In [25]:
#@title Double click here for a sample solution

# Return values in the array under 40
print("Values under 40 in array =", x[x<40])

Values under 40 in array = [29 39 36  5 29 39  6]
